name: hlweb_production_remote

services:

  hlweb_production:
    image: jreichler/${COMPOSE_PROJECT_NAME}:latest
    container_name: ${COMPOSE_PROJECT_NAME}
    build:
      dockerfile: docker/${COMPOSE_PROJECT_NAME}/Dockerfile
      context: ../../
      tags:
        - jreichler/${COMPOSE_PROJECT_NAME}:v4.66

    #ATTN: This command will OVERRIDE any CMD in the Dockerfile; currently we use same values
    #command: /install_scripts/run_mainservices.sh

    # disable for interactive shell testing
    restart: always

    volumes:
      - media_games:/media/games
      - db:/db
      - jrlogs:/jrlogs
      - letsencrypt:/etc/letsencrypt

    ports:
      # TIP: see also the Dockerfile for exposing ports
      - "80:80"
      - "443:443"
      # 8000 should not be needed since we are accessing via nginx at 80 and 443
      #- "8000:8000"

    environment:
      - COMPOSE_PROJECT_NAME
      - TZ=America/Chicago


# create named volumes used above
volumes:
  media_games:
  db:
  jrlogs:
  letsencrypt:
